services:
  - type: web
    name: hashstock-sheet-worker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://paelbarlmayswqilhoxa.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_6Kz2o4DWlxhBgc7oyDt2AA_KmphGK-h
