const fs = require('fs');
let lines = fs.readFileSync('src/App.jsx', 'utf8').split('\n');

const startIdx = lines.findIndex((l, i) => i > 3250 && l.includes('<div className="shelf-rack-grid">'));
const endIdx = lines.findIndex((l, i) => i > startIdx && l.includes('</div>') && lines[i+1]?.includes('</div>') && lines[i+2]?.includes(');') && lines[i+3]?.includes('})'));

console.log('startIdx:', startIdx, 'endIdx:', endIdx);

if (startIdx !== -1 && endIdx !== -1) {
  const replacement = [
    `                                        {(() => {`,
    `                                           const layoutMeta = (() => {`,
    `                                             try { return JSON.parse(localStorage.getItem("hs_layout_" + shelfName) || "{}"); } catch(e) { return {}; }`,
    `                                           })();`,
    `                                           const slotsPerVao = layoutMeta.machinesPerLevel || 6;`,
    `                                           const vaos = [];`,
    `                                           for (let i = 0; i < list.length; i += slotsPerVao) {`,
    `                                             vaos.push(list.slice(i, i + slotsPerVao));`,
    `                                           }`,
    ``,
    `                                           return (`,
    `                                             <div style={{display:'flex', flexDirection:'column', gap:12}}>`,
    `                                               {vaos.map((vaoList, vaoIdx) => (`,
    `                                                 <div key={vaoIdx} style={{background:'#111827', borderRadius:10, padding:12, border:'1px solid #1f2937'}}>`,
    `                                                   <div style={{fontSize:11, fontWeight:800, color:C.subtle, marginBottom:10, display:'flex', justifyContent:'space-between', alignItems:'center'}}>`,
    `                                                     <span>📍 VÃO #\${vaoIdx + 1} (\${vaoList.length} posições)</span>`,
    `                                                     <span style={{fontSize:10, color:C.muted}}>Slots #\${vaoList[0]?.notes} - #\${vaoList[vaoList.length-1]?.notes}</span>`,
    `                                                   </div>`,
    `                                                   <div className="shelf-rack-grid" style={{display:'flex', flexWrap:'wrap', gap:8}}>`,
    `                                                     {vaoList.map(m => {`,
    `                                                       const stat = farmStatus[m.ip] || null;`,
    `                                                       const isDummy = m.sn && m.sn.startsWith("FARM-");`,
    `                                                       const isOnline = stat && stat.status !== 'offline';`,
    `                                                       const isMining = isOnline && stat.status === 'mining';`,
    `                                                       const machineModelName = (m.model && m.model !== "Antminer S19j Pro") ? m.model : (stat?.model || m.model || "Whatsminer M30S");`,
    `                                                       `,
    `                                                       let bg = '#17202e'; `,
    `                                                       let textColor = '#94a3b8'; `,
    `                                                       let borderStyle = '1px solid #334155';`,
    `                                                       let ledColor = '#475569';`,
    `                                                       let borderGlow = 'none';`,
    ``,
    `                                                       if (m.ip) {`,
    `                                                           if (isMining) {`,
    `                                                               bg = '#064e3b';`,
    `                                                               textColor = '#6ee7b7';`,
    `                                                               borderStyle = '1px solid #10b981';`,
    `                                                               borderGlow = '0 0 12px rgba(16,185,129,0.4)';`,
    `                                                               ledColor = '#10b981';`,
    `                                                           } else if (isOnline) {`,
    `                                                               bg = '#451a03';`,
    `                                                               textColor = '#fde68a';`,
    `                                                               borderStyle = '1px solid #f59e0b';`,
    `                                                               borderGlow = '0 0 10px rgba(245,158,11,0.3)';`,
    `                                                               ledColor = '#f59e0b';`,
    `                                                           } else {`,
    `                                                               bg = '#1e1b2e';`,
    `                                                               textColor = '#cbd5e1';`,
    `                                                               borderStyle = '1px solid #475569';`,
    `                                                               ledColor = '#ef4444';`,
    `                                                           }`,
    `                                                       }`,
    ``,
    `                                                       const shortIP = m.ip ? m.ip.split('.').slice(2).join('.') : null;`,
    `                                                       let valToShow = "Slot #" + m.notes;`,
    `                                                       if (viewMode === 'temp') {`,
    `                                                           valToShow = isOnline && stat.temp ? stat.temp + '°C' : '--';`,
    `                                                       } else if (viewMode === 'hashrate') {`,
    `                                                           valToShow = isOnline && stat.hashrate ? stat.hashrate.toFixed(0) + ' TH' : '--';`,
    `                                                       }`,
    ``,
    `                                                       const snMismatch = isOnline && stat.sn && m.sn && !isDummy && stat.sn.trim().toUpperCase() !== m.sn.trim().toUpperCase();`,
    ``,
    `                                                       return (`,
    `                                                           <div `,
    `                                                              key={m._id} `,
    `                                                              className="shelf-slot-box"`,
    `                                                              onDoubleClick={(e) => { e.stopPropagation(); if (m.ip) window.open('http://' + m.ip, '_blank'); }}`,
    `                                                              onClick={() => openSlotDetailsModal(m)}`,
    `                                                              style={{`,
    `                                                                  minWidth: 85,`,
    `                                                                  height: 56,`,
    `                                                                  padding: '6px 8px',`,
    `                                                                  fontSize: 11,`,
    `                                                                  background: bg,`,
    `                                                                  color: textColor,`,
    `                                                                  boxShadow: borderGlow,`,
    `                                                                  border: snMismatch ? "2px solid " + C.amber : borderStyle,`,
    `                                                                  display: 'flex',`,
    `                                                                  flexDirection: 'column',`,
    `                                                                  justifyContent: 'center',`,
    `                                                                  alignItems: 'center',`,
    `                                                                  borderRadius: 8,`,
    `                                                                  position: 'relative'`,
    `                                                              }}`,
    `                                                           >`,
    `                                                               <div style={{position:'absolute', top:4, right:4, width:6, height:6, borderRadius:'50%', background: ledColor}} />`,
    `                                                               <div style={{fontWeight: 900, fontSize: 11}}>{valToShow}</div>`,
    `                                                               <div style={{fontSize: 10, color: shortIP ? C.accent : C.muted, marginTop: 3, fontWeight: 800}}>`,
    `                                                                 {shortIP ? "🌐 " + shortIP : "🌐 Sem IP"}`,
    `                                                               </div>`,
    ``,
    `                                                               {/* Tooltip Card */}`,
    `                                                               <div className="shelf-slot-tooltip">`,
    `                                                                   <div style={{fontWeight:900, color:C.accent, fontSize:12, marginBottom:4, display:'flex', justifyContent:'space-between'}}>`,
    `                                                                       <span>Slot #\${m.notes} · \${machineModelName}</span>`,
    `                                                                       <span style={{color: isOnline ? C.green : C.red}}>\${isOnline ? (isMining ? 'MINANDO' : 'OCIOSO') : 'OFFLINE'}</span>`,
    `                                                                   </div>`,
    `                                                                   <div style={{height:1, background:C.border, margin:'4px 0'}} />`,
    `                                                                   <div>🌐 IP: \${m.ip || 'Sem IP (Clique para configurar)'}</div>`,
    `                                                                   <div>💻 Modelo: \${machineModelName}</div>`,
    `                                                                   <div>📦 SN Carcaça: \${isDummy ? '(Vazio)' : m.sn}</div>`,
    `                                                                   \${isOnline ? \``,
    `                                                                       <div>📦 SN Físico: \${stat.sn || '--'}</div>`,
    `                                                                       <div>⏱️ Uptime: \${formatUptime(stat.uptime)}</div>`,
    `                                                                       <div>⛏️ Hashrate: \${stat.hashrate ? stat.hashrate.toFixed(1) + ' TH/s' : '--'}</div>`,
    `                                                                       <div>🌡️ Temp: \${stat.temp ? stat.temp + '°C' : '--'}</div>`,
    `                                                                   \` : ''}`,
    `                                                                   <div style={{fontSize:9, color:C.subtle, marginTop:4}}>(Clique para gerenciar IP e SN)</div>`,
    `                                                               </div>`,
    `                                                           </div>`,
    `                                                       );`,
    `                                                     })}`,
    `                                                   </div>`,
    `                                                 </div>`,
    `                                               ))}`,
    `                                             </div>`,
    `                                           );`,
    `                                        })()}`
  ];

  lines.splice(startIdx, endIdx - startIdx + 1, ...replacement);
  fs.writeFileSync('src/App.jsx', lines.join('\n'), 'utf8');
  console.log("REPLACED SHELF RACK GRID BY VAOS SUCCESS");
}
